# Generated by Django 4.2 on 2025-07-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ogrn', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('ownership_score', models.FloatField()),
                ('details', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownership_checker.organization')),
            ],
        ),
    ]
