# Generated by Django 4.2 on 2025-07-09 09:06

from django.db import migrations, models
import ownership_checker.models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True, validators=[ownership_checker.models.validate_ogrn]),
        ),
    ]
